[package]
name = "ft6x36"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = { version = "^0.2" }
num_enum = { version = "0.5.6", default-features = false }
